# Generated by Django 5.1.7 on 2025-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
    ]
