# Generated by Django 5.1.7 on 2025-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='device',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
