# Generated by Django 5.1.7 on 2025-04-11 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_average_rating_device_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
